name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, rust]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        pip install -r python_script/requirements.txt
    
    - name: Run Python script
      if: matrix.language == 'python'
      run: python python_script/main.py

    - name: Set up Rust
      if: matrix.language == 'rust'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build Rust
      if: matrix.language == 'rust'
      run: cargo build --manifest-path=rust_script/Cargo.toml --release

    - name: Run Rust script
      if: matrix.language == 'rust'
      run: cargo run --manifest-path=rust_script/Cargo.toml --release
